# -*- coding: utf-8 -*-
"""Session1:Important Libraries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10O6By963LLEUtVGqcDMpAwxRKJ81lpBr

## ACM-W, MTC and MSPs present: Data Science Series - Session 1: The Numpy Stack (Numpy and Matplotlib)

## Section 1: Numpy
"""

import numpy as np

#Creating a numpy array from python array
l = [1,2,3,4]
l_np = np.array(l)
print("1 dimensional vector: ",l_np)
print("Shape of vector: ",l_np.shape)
print("Number of dimensions: ",l_np.ndim)
print("Size of vector",l_np.size,"\n")
l_2 = [[1,2],[3,4]]
l_2_np = np.array(l_2)
print("2 dimensional matrix: ",l_2_np)
print("Shape of array: ",l_2_np.shape)
print("Number of dimensions: ",l_2_np.ndim)
print("Size of matrix",l_2_np.size,"\n")
#Creating numpy array of random number
l_3_np = np.random.rand(3,3)
print("Creating a random matrix of values between 0 and 1:\n",l_3_np,"\n")

l_4_np = np.random.randint(10,size=(3,3))
print("Creating a random matrix of integer values between 0 and 10",l_4_np,"\n")

l_5_np = np.random.randn(3,3)
print("Creating a random matrix of values between 0 and 1 with mean around 0 and variance around 1",l_5_np,"\n")
print("MEAN:",l_5_np.mean())
print("VARIANCE:",l_5_np.var())

#Vector: D=1
#Matrix: D>2
v = [1,0.5,4]
v_np = np.array(v)
print(v_np+2)
print(v_np/2)
print(v_np*2)
print(v_np-2)

#Two numpy operations
a = np.array([1,2,3])
b = np.array([4,5,6])
#Arithmetic
print("Arithmetic Operations:")
print(a+b)
print(a-b)
print(a*b)
print(a/b)
#Stacking two vectors
print("\nStacking two vectors.")
print("Horizontal: ",np.hstack((a,b)))
print("Vertical: ",np.vstack((a,b)))
#Creating plain matrices of zeroes and ones
print("\nCreating zero matrix of (3,3), one matrix of (3,3) and identity matrix of (3,3).")
zero = np.zeros((3,3))
print("Zero Matrix\n",zero)
one = np.ones((3,3))
print("One Matrix\n",one)
id = np.eye(3) #Identity Matrix
print("Identity Matrix\n",id)

#Slicing/Indexing Numpy Arrays
s = np.random.randint(10,size=(3,3))
print("Random Matrix:\n",s,"\n")

print("Printing out the first row: ",s[0,:])
print("Printing out the first row: ",s[:,0])
print("Printing a 2x2 out of the 3x3 matrix: ",s[np.ix_([0,1],[0,1])])
print("Printing a 2x2 out of the 3x3 matrix: ",s[0:2,0:2])

"""## Section 2: Matplotlib"""

import matplotlib.pyplot as plt

fig = plt.figure()
ax = plt.axes()
#Let us plot a basic curve f(x)=x;
plt.title("f(x)=x")
plt.xlabel("x")
plt.ylabel("f(x)=y=x")
plt.plot([1,2,3],[1,2,3])

#Lets now make a scatter curve
fig2 = plt.figure()
plt.title("Scatter Plot")
rad_x = np.random.rand(200)
rad_y = np.random.rand(200)
plt.scatter(rad_x,rad_y)

print(np.random.randint(2,6,size=(2,2)))